# overlay_rgb_mgm_dpe.yaml
_BASE_: ../mgm_swin_convnext_tiny.yaml
MODEL:
  FINETUNE_WEIGHTS: "MGM_Mask2Former/pretrained-checkpoint/0825_10K_0905_10K.pth"
  MGM:
    ENABLED: True
  DPE:
    ENABLED: True

SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 1e-5
  STEPS: (18000, 19000)
  MAX_ITER: 20000
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 5000
